server:
  port: 8080

spring :
  datasource :
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: zqctest
    password: zqc1234
    driver-class-name : com.mysql.jdbc.Driver

mybatis :

  config-location: classpath:mybatis-config.xml